/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dtos.UsuarioDTO;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import negocio.IUsuarioNegocio;
import negocio.NegocioException;
import presentacion.Navegador;

/**
 *
 * @author cinca
 */
public class FrmActualizarPerfil extends javax.swing.JFrame {

    private UsuarioDTO usuarioActual;
    private Navegador navegador;
    private IUsuarioNegocio usuarioNegocio;
    

    /**
     * Creates new form FrmRegistrarse
     */
    public FrmActualizarPerfil() {
        initComponents();
        setLocationRelativeTo(null);
    }

   
    public FrmActualizarPerfil(UsuarioDTO usuarioActual, Navegador navegador, IUsuarioNegocio usuarioNegocio) {
        this.usuarioActual = usuarioActual;
        this.navegador = navegador;
        this.usuarioNegocio = usuarioNegocio;

        initComponents();
        setLocationRelativeTo(null);

        cargarDatosActuales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlFondo = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        LblCorreo = new javax.swing.JLabel();
        LblContra = new javax.swing.JLabel();
        TxTcorreo = new javax.swing.JTextField();
        TxTContra = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        LblUsuario = new javax.swing.JLabel();
        LblFoto = new javax.swing.JLabel();
        txtURL = new javax.swing.JTextField();
        btnElegir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlFondo.setBackground(new java.awt.Color(51, 51, 51));

        LblTitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        LblTitulo.setText("Registro");

        LblCorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblCorreo.setText("Correo electronico");

        LblContra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblContra.setText("Contraseña");

        TxTcorreo.setBackground(new java.awt.Color(0, 0, 0));
        TxTcorreo.setForeground(new java.awt.Color(255, 255, 255));

        TxTContra.setBackground(new java.awt.Color(0, 0, 0));
        TxTContra.setForeground(new java.awt.Color(255, 255, 255));

        btnGuardar.setBackground(new java.awt.Color(109, 79, 130));
        btnGuardar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnGuardar.setText("Guardar cambios");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        txtUsuario.setBackground(new java.awt.Color(0, 0, 0));
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));

        LblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblUsuario.setText("Nombre de Usuario");

        LblFoto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblFoto.setText("Foto de Perfil (Opcional)");

        txtURL.setBackground(new java.awt.Color(0, 0, 0));
        txtURL.setForeground(new java.awt.Color(255, 255, 255));

        btnElegir.setBackground(new java.awt.Color(109, 79, 130));
        btnElegir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnElegir.setText("Elegir");
        btnElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(109, 79, 130));
        btnCancelar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlFondoLayout = new javax.swing.GroupLayout(PnlFondo);
        PnlFondo.setLayout(PnlFondoLayout);
        PnlFondoLayout.setHorizontalGroup(
            PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFondoLayout.createSequentialGroup()
                .addGroup(PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlFondoLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblFoto)
                            .addComponent(TxTContra, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblContra)
                            .addComponent(TxTcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PnlFondoLayout.createSequentialGroup()
                                .addComponent(txtURL, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnElegir))
                            .addComponent(LblCorreo)
                            .addComponent(LblTitulo)
                            .addComponent(LblUsuario)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PnlFondoLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        PnlFondoLayout.setVerticalGroup(
            PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFondoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(LblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(LblCorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxTcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblContra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxTContra, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblFoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtURL, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnElegir, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            String nombreUsuario = txtUsuario.getText().trim();

            if (nombreUsuario.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El nombre de usuario no puede estar vacio.", "Datos incompletos", JOptionPane.WARNING_MESSAGE);
                return;
            }

            usuarioActual.setUsuario(nombreUsuario);
            usuarioActual.setImagen(txtURL.getText().trim());

            UsuarioDTO actualizado = usuarioNegocio.actualizarPerfil(usuarioActual);
            navegador.actualizarUsuarioActual(actualizado);

            JOptionPane.showMessageDialog(this, "Perfil actualizado correctamente.");
            navegador.abrirPerfil(this);

        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirActionPerformed
        JFileChooser fChooser = new JFileChooser();
        
        int resultado = fChooser.showOpenDialog(this);
        
        if(resultado == JFileChooser.APPROVE_OPTION) {
           File imagenSeleccionada = fChooser.getSelectedFile();
           
           txtURL.setText(imagenSeleccionada.getAbsolutePath());
        }
    }//GEN-LAST:event_btnElegirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        navegador.abrirPerfil(this);
    }//GEN-LAST:event_btnCancelarActionPerformed

    
    /**
     * Llena los campos con la informacion actual del usuario y el usuario solo 
     * edite lo que quiera cambiar.
     */
    private void cargarDatosActuales() {
        txtUsuario.setText(usuarioActual.getUsuario());
        TxTcorreo.setText(usuarioActual.getCorreo());
       // TxTcorreo.setEditable(false); 
       // TxTContra.setEditable(false); 
        txtURL.setText(usuarioActual.getImagen());
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblContra;
    private javax.swing.JLabel LblCorreo;
    private javax.swing.JLabel LblFoto;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JLabel LblUsuario;
    private javax.swing.JPanel PnlFondo;
    private javax.swing.JTextField TxTContra;
    private javax.swing.JTextField TxTcorreo;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnElegir;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField txtURL;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
