/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dtos.AlbumDTO;
import dtos.CancionDTO;
import dtos.CancionDetallesDTO;
import dtos.UsuarioDTO;
import java.awt.Color;
import java.awt.Dimension;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import presentacion.Navegador;
import presentacion.pnlAlbum;
import presentacion.pnlCancion;

/**
 *
 * @author cinca
 */
public class FrmInicio extends javax.swing.JFrame {

    private negocio.IAlbumNegocio albumNegocio;
    //private negocio.IArtistaNegocio artistaNegocio;
    private negocio.ICancionNegocio cancionNegocio;
    private UsuarioDTO usuarioDTO;
    private Navegador navegador;

    /**
     * Creates new form FrmInicio
     */
    public FrmInicio() {
        initComponents();
        setMinimumSize(new java.awt.Dimension(1080, 650));
        setLocationRelativeTo(null);
    }

    public FrmInicio(UsuarioDTO usuarioDTO, Navegador navegador) {
        this.usuarioDTO = usuarioDTO;
        this.navegador = navegador;

        persistencia.IConexionDAO conexion = new persistencia.ConexionDAO();
        this.albumNegocio = new negocio.AlbumNegocio(new persistencia.AlbumDAO(conexion));
        //this.artistaNegocio = new negocio.ArtistaNegocio(new persistencia.ArtistaDAO(conexion));
        this.cancionNegocio = new negocio.CancionNegocio(new persistencia.CancionDAO(conexion));

        initComponents();

        this.setMinimumSize(new Dimension(1080, 650));
        this.setLocationRelativeTo(null);
        pnlMenuLateral1.configurarSesion(usuarioDTO, navegador);

        pnlResultados.setLayout(new BoxLayout(pnlResultados, BoxLayout.Y_AXIS));
        pnlResultados.setBackground(new Color(51, 51, 51));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlMenuLateral1 = new presentacion.PnlMenuLateral();
        jPanel2 = new javax.swing.JPanel();
        lblTipo = new javax.swing.JLabel();
        TxTBuscador1 = new javax.swing.JTextField();
        BtnBuscar1 = new javax.swing.JButton();
        LblInicio2 = new javax.swing.JLabel();
        cbxGenero = new javax.swing.JComboBox<>();
        lblGenero1 = new javax.swing.JLabel();
        cbxTipo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlResultados = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(817, 91));

        lblTipo.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(255, 255, 255));
        lblTipo.setText("Tipo:");

        TxTBuscador1.setBackground(new java.awt.Color(0, 0, 0));
        TxTBuscador1.setForeground(new java.awt.Color(255, 255, 255));

        BtnBuscar1.setBackground(new java.awt.Color(109, 79, 130));
        BtnBuscar1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        BtnBuscar1.setForeground(new java.awt.Color(255, 255, 255));
        BtnBuscar1.setText("Buscar");
        BtnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscar1ActionPerformed(evt);
            }
        });

        LblInicio2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        LblInicio2.setForeground(new java.awt.Color(255, 255, 255));
        LblInicio2.setText("Inicio");

        cbxGenero.setBackground(new java.awt.Color(109, 79, 130));
        cbxGenero.setForeground(new java.awt.Color(255, 255, 255));
        cbxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Rock Alternativo", "Reggaeton" }));
        cbxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxGeneroActionPerformed(evt);
            }
        });

        lblGenero1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lblGenero1.setForeground(new java.awt.Color(255, 255, 255));
        lblGenero1.setText("Genero:");

        cbxTipo.setBackground(new java.awt.Color(109, 79, 130));
        cbxTipo.setForeground(new java.awt.Color(255, 255, 255));
        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Album", "Artista", "Cancion" }));
        cbxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TxTBuscador1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(LblInicio2)
                    .addContainerGap(684, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(lblGenero1)
                    .addContainerGap(690, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxTBuscador1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(LblInicio2)
                    .addContainerGap(69, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(93, Short.MAX_VALUE)
                    .addComponent(lblGenero1)
                    .addContainerGap()))
        );

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));

        pnlResultados.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout pnlResultadosLayout = new javax.swing.GroupLayout(pnlResultados);
        pnlResultados.setLayout(pnlResultadosLayout);
        pnlResultadosLayout.setHorizontalGroup(
            pnlResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 825, Short.MAX_VALUE)
        );
        pnlResultadosLayout.setVerticalGroup(
            pnlResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(pnlResultados);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMenuLateral1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
                        .addGap(11, 11, 11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlMenuLateral1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscar1ActionPerformed
        try {
            String texto = TxTBuscador1.getText().trim();
            String genero = cbxGenero.getSelectedItem().toString();
            String tipo = cbxTipo.getSelectedItem().toString();

            if (genero.equals("Todos")) {
                genero = null;
            }

            pnlResultados.removeAll();

            if (tipo.equals("Todos") || tipo.equals("Album")) {
                List<AlbumDTO> albumes = albumNegocio.buscarAlbumes(texto, genero, null);
                for (AlbumDTO album : albumes) {
                    pnlAlbum panelItem = new pnlAlbum(album);
                    panelItem.setBorder(BorderFactory.createTitledBorder(
                            BorderFactory.createLineBorder(new Color(109, 79, 130), 2),
                            "ÁLBUM",
                            javax.swing.border.TitledBorder.LEFT,
                            javax.swing.border.TitledBorder.TOP,
                            new java.awt.Font("Segoe UI Black", 0, 12),
                            Color.WHITE));
                    pnlResultados.add(panelItem);
                    pnlResultados.add(Box.createRigidArea(new Dimension(0, 15)));
                }
            }

//            if (tipo.equals("Todos") || tipo.equals("Artista")) {
//                List<ArtistaDTO> artistas = artistaNegocio.buscarArtistas(texto, genero);
//                for (ArtistaDTO artista : artistas) {
//                    pnlArtista panelItem = new pnlArtista(artista); // Asumiendo que tienes este panel creado
//                    panelItem.setBorder(BorderFactory.createTitledBorder(
//                            BorderFactory.createLineBorder(new Color(109, 79, 130), 2),
//                            "ARTISTA",
//                            javax.swing.border.TitledBorder.LEFT,
//                            javax.swing.border.TitledBorder.TOP,
//                            new java.awt.Font("Segoe UI Black", 0, 12),
//                            Color.WHITE));
//                    pnlResultados.add(panelItem);
//                    pnlResultados.add(Box.createRigidArea(new Dimension(0, 15)));
//                }
//            }
            if (tipo.equals("Todos") || tipo.equals("Cancion")) {
                List<CancionDetallesDTO> canciones = cancionNegocio.buscarCanciones(texto, genero);
                for (CancionDetallesDTO cancion : canciones) {
                    pnlCancion panelItem = new pnlCancion(cancion);
                    panelItem.setBorder(BorderFactory.createTitledBorder(
                            BorderFactory.createLineBorder(new Color(109, 79, 130), 2),
                            "CANCIÓN",
                            javax.swing.border.TitledBorder.LEFT,
                            javax.swing.border.TitledBorder.TOP,
                            new java.awt.Font("Segoe UI Black", 0, 12),
                            Color.WHITE));
                    pnlResultados.add(panelItem);
                    pnlResultados.add(Box.createRigidArea(new Dimension(0, 15)));
                }
            }

            pnlResultados.revalidate();
            pnlResultados.repaint();

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error en la búsqueda: " + ex.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_BtnBuscar1ActionPerformed

    private void cbxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxGeneroActionPerformed

    private void cbxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar1;
    private javax.swing.JLabel LblInicio2;
    private javax.swing.JTextField TxTBuscador1;
    private javax.swing.JComboBox<String> cbxGenero;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGenero1;
    private javax.swing.JLabel lblTipo;
    private presentacion.PnlMenuLateral pnlMenuLateral1;
    private javax.swing.JPanel pnlResultados;
    // End of variables declaration//GEN-END:variables
}
