/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dtos.UsuarioDTO;
import negocio.AlbumNegocio;
import negocio.CancionNegocio;
import negocio.IAlbumNegocio;
import negocio.ICancionNegocio;
import negocio.IUsuarioNegocio;
import negocio.NegocioException;
import negocio.UsuarioNegocio;
import persistencia.AlbumDAO;
import persistencia.CancionDAO;
import persistencia.ConexionDAO;
import persistencia.IAlbumDAO;
import persistencia.ICancionDAO;
import persistencia.IConexionDAO;
import persistencia.IUsuarioDAO;
import persistencia.UsuarioDAO;

/**
 *
 * @author piña
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PnlFondo = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        LblCorreo = new javax.swing.JLabel();
        LblContra = new javax.swing.JLabel();
        TxTcorreo = new javax.swing.JTextField();
        TxTContra = new javax.swing.JTextField();
        BtnEntrar = new javax.swing.JButton();
        BtnRegistro = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlFondo.setBackground(new java.awt.Color(51, 51, 51));

        LblTitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        LblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        LblTitulo.setText("Iniciar sesion");

        LblCorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        LblCorreo.setText("Correo electronico");

        LblContra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblContra.setForeground(new java.awt.Color(255, 255, 255));
        LblContra.setText("Contraseña");

        TxTcorreo.setBackground(new java.awt.Color(0, 0, 0));
        TxTcorreo.setForeground(new java.awt.Color(255, 255, 255));

        TxTContra.setBackground(new java.awt.Color(0, 0, 0));
        TxTContra.setForeground(new java.awt.Color(255, 255, 255));

        BtnEntrar.setBackground(new java.awt.Color(109, 79, 130));
        BtnEntrar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        BtnEntrar.setText("Entrar");
        BtnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEntrarActionPerformed(evt);
            }
        });

        BtnRegistro.setBackground(new java.awt.Color(109, 79, 130));
        BtnRegistro.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        BtnRegistro.setText("Registrarse");
        BtnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlFondoLayout = new javax.swing.GroupLayout(PnlFondo);
        PnlFondo.setLayout(PnlFondoLayout);
        PnlFondoLayout.setHorizontalGroup(
            PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFondoLayout.createSequentialGroup()
                .addGroup(PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlFondoLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxTContra, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblContra)
                            .addComponent(LblCorreo)
                            .addComponent(LblTitulo)
                            .addComponent(TxTcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PnlFondoLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        PnlFondoLayout.setVerticalGroup(
            PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFondoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(LblTitulo)
                .addGap(27, 27, 27)
                .addComponent(LblCorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxTcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LblContra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxTContra, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(BtnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistroActionPerformed
        FrmRegistrarse reguistro = new FrmRegistrarse();
        reguistro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnRegistroActionPerformed

    private void BtnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEntrarActionPerformed

        String correoLog = TxTcorreo.getText().trim();
        String contrasenaLog = new String(TxTContra.getText());

        if (correoLog.isEmpty() || contrasenaLog.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, llena todos los campos.", "Campos vacíos", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        IConexionDAO conexionDAO = new ConexionDAO();

        ICancionDAO cancionDAO = new CancionDAO(conexionDAO);
        ICancionNegocio cancionNegocio = new CancionNegocio(cancionDAO);

        IAlbumDAO albumDAO = new AlbumDAO(conexionDAO);
        IAlbumNegocio albumNegocio = new AlbumNegocio(albumDAO);

        IUsuarioDAO usuarioDAO = new UsuarioDAO(conexionDAO);
        IUsuarioNegocio usuarioNegocio = new UsuarioNegocio(usuarioDAO);

        try {
            UsuarioDTO usuario = usuarioNegocio.buscar(correoLog, contrasenaLog);

            if (usuario == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Correo o contraseña incorrectos.", "Error de Autenticación", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            Navegador navegador = new Navegador(usuario, usuarioNegocio, cancionNegocio, albumNegocio);
            navegador.abrirInicio(this);

        } catch (NegocioException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de Autenticación", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_BtnEntrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEntrar;
    private javax.swing.JButton BtnRegistro;
    private javax.swing.JLabel LblContra;
    private javax.swing.JLabel LblCorreo;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JPanel PnlFondo;
    private javax.swing.JTextField TxTContra;
    private javax.swing.JTextField TxTcorreo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
