/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author piña
 */
public class FrmRegistrarse extends javax.swing.JFrame {

    /**
     * Creates new form FrmRegistrarse
     */
    public FrmRegistrarse() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlFondo = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        LblCorreo = new javax.swing.JLabel();
        LblContra = new javax.swing.JLabel();
        TxTcorreo = new javax.swing.JTextField();
        TxTContra = new javax.swing.JTextField();
        BtnRegistro = new javax.swing.JButton();
        TxTUsuario = new javax.swing.JTextField();
        LblUsuario = new javax.swing.JLabel();
        LblFoto = new javax.swing.JLabel();
        TxTContra1 = new javax.swing.JTextField();
        BtnRegistro1 = new javax.swing.JButton();
        BtnInicioSecion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlFondo.setBackground(new java.awt.Color(51, 51, 51));

        LblTitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        LblTitulo.setText("Registro");

        LblCorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblCorreo.setText("Correo electronico");

        LblContra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblContra.setText("Contraseña");

        TxTcorreo.setBackground(new java.awt.Color(0, 0, 0));
        TxTcorreo.setForeground(new java.awt.Color(255, 255, 255));

        TxTContra.setBackground(new java.awt.Color(0, 0, 0));
        TxTContra.setForeground(new java.awt.Color(255, 255, 255));

        BtnRegistro.setBackground(new java.awt.Color(109, 79, 130));
        BtnRegistro.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        BtnRegistro.setText("Registrarse");
        BtnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistroActionPerformed(evt);
            }
        });

        TxTUsuario.setBackground(new java.awt.Color(0, 0, 0));
        TxTUsuario.setForeground(new java.awt.Color(255, 255, 255));

        LblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblUsuario.setText("Nombre de Usuario");

        LblFoto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblFoto.setText("Foto de Perfil (Opcional)");

        TxTContra1.setBackground(new java.awt.Color(0, 0, 0));
        TxTContra1.setForeground(new java.awt.Color(255, 255, 255));

        BtnRegistro1.setBackground(new java.awt.Color(109, 79, 130));
        BtnRegistro1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        BtnRegistro1.setText("Elegir");
        BtnRegistro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistro1ActionPerformed(evt);
            }
        });

        BtnInicioSecion.setBackground(new java.awt.Color(109, 79, 130));
        BtnInicioSecion.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        BtnInicioSecion.setText("Iniciar Sesion");
        BtnInicioSecion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInicioSecionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlFondoLayout = new javax.swing.GroupLayout(PnlFondo);
        PnlFondo.setLayout(PnlFondoLayout);
        PnlFondoLayout.setHorizontalGroup(
            PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFondoLayout.createSequentialGroup()
                .addGroup(PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlFondoLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblFoto)
                            .addComponent(TxTContra, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblContra)
                            .addComponent(TxTcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PnlFondoLayout.createSequentialGroup()
                                .addComponent(TxTContra1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnRegistro1))
                            .addComponent(LblCorreo)
                            .addComponent(LblTitulo)
                            .addComponent(LblUsuario)
                            .addComponent(TxTUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PnlFondoLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnInicioSecion, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        PnlFondoLayout.setVerticalGroup(
            PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFondoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(LblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxTUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(LblCorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxTcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblContra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxTContra, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblFoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxTContra1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRegistro1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnInicioSecion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRegistroActionPerformed

    private void BtnRegistro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRegistro1ActionPerformed

    private void BtnInicioSecionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInicioSecionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnInicioSecionActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnInicioSecion;
    private javax.swing.JButton BtnRegistro;
    private javax.swing.JButton BtnRegistro1;
    private javax.swing.JLabel LblContra;
    private javax.swing.JLabel LblCorreo;
    private javax.swing.JLabel LblFoto;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JLabel LblUsuario;
    private javax.swing.JPanel PnlFondo;
    private javax.swing.JTextField TxTContra;
    private javax.swing.JTextField TxTContra1;
    private javax.swing.JTextField TxTUsuario;
    private javax.swing.JTextField TxTcorreo;
    // End of variables declaration//GEN-END:variables
}
