/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import dtos.AlbumDTO;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;

/**
 *
 * @author luisf
 */
public class pnlAlbum extends javax.swing.JPanel {

    private AlbumDTO albumDTO;

    /**
     * Creates new form pnlCancion
     */
    public pnlAlbum(AlbumDTO albumDTO) {
        initComponents();

        this.albumDTO = albumDTO;

        if (albumDTO != null) {

            jLabelTitulo.setText(albumDTO.getNombre());
            jLabelArtista.setText(albumDTO.getNombreArtista());
            jLabelGenero.setText(albumDTO.getNombreGenero());
            pnlImagen.setLayout(new BorderLayout());
            lblImagen.setHorizontalAlignment(SwingConstants.CENTER);
            lblImagen.setVerticalAlignment(SwingConstants.CENTER);
            pnlImagen.removeAll();
            pnlImagen.add(lblImagen, BorderLayout.CENTER);
            
            if (albumDTO.getFechaLanzamiento() != null) {
                java.text.SimpleDateFormat formateador = new java.text.SimpleDateFormat("dd/MM/yyyy");
                String fechaTexto = formateador.format(albumDTO.getFechaLanzamiento());
                jLabelFecha.setText(fechaTexto);
                cargarImagen(albumDTO.getImagenAlbum());
            } else {
                jLabelFecha.setText("Sin fecha");
            }
        }

        this.setMaximumSize(new java.awt.Dimension(821, 184));
    }
    
    /**
     * Carga la imagen de  la portada del album.
     */
    private void cargarImagen(String rutaImagen) {
        if (rutaImagen == null || rutaImagen.isBlank()) {
            lblImagen.setIcon(null);
            lblImagen.setText("Sin imagen");
            return;
        }

        URL url = getClass().getResource("/imagenes/" + rutaImagen);

        if (url == null) {
            lblImagen.setIcon(null);
            lblImagen.setText("Imagen no disponible");
            return;
        }

        ImageIcon icono = new ImageIcon(url);
        Image imagen = icono.getImage().getScaledInstance(120, 120, Image.SCALE_SMOOTH);

        lblImagen.setIcon(new ImageIcon(imagen));
        lblImagen.setText("");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlImagen = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelGenero = new javax.swing.JLabel();
        jLabelArtista = new javax.swing.JLabel();
        btnFavorito = new javax.swing.JToggleButton();
        BtnSeleccionar = new javax.swing.JButton();
        jLabelFecha = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(109, 79, 130), 3));
        setForeground(new java.awt.Color(109, 79, 130));
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(821, 184));

        lblImagen.setText("Imagen");

        javax.swing.GroupLayout pnlImagenLayout = new javax.swing.GroupLayout(pnlImagen);
        pnlImagen.setLayout(pnlImagenLayout);
        pnlImagenLayout.setHorizontalGroup(
            pnlImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImagenLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblImagen)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        pnlImagenLayout.setVerticalGroup(
            pnlImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImagenLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblImagen)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Nombre de Album");

        jLabelGenero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelGenero.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGenero.setText("Genero");

        jLabelArtista.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelArtista.setForeground(new java.awt.Color(255, 255, 255));
        jLabelArtista.setText("Artista");

        btnFavorito.setText("★");
        btnFavorito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFavoritoActionPerformed(evt);
            }
        });

        BtnSeleccionar.setBackground(new java.awt.Color(109, 79, 130));
        BtnSeleccionar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        BtnSeleccionar.setForeground(new java.awt.Color(255, 255, 255));
        BtnSeleccionar.setText("Seleccionar");
        BtnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSeleccionarActionPerformed(evt);
            }
        });

        jLabelFecha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelFecha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFecha.setText("Fecha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(pnlImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelGenero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 447, Short.MAX_VALUE)
                        .addComponent(BtnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelArtista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFavorito)
                        .addGap(76, 76, 76))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTitulo)
                            .addComponent(jLabelFecha))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelGenero)
                            .addComponent(BtnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelArtista)
                            .addComponent(btnFavorito, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelFecha)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFavoritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavoritoActionPerformed
        if (btnFavorito.isSelected()) {
            btnFavorito.setForeground(new Color(147, 112, 219));
            // negocio.agregarFavorito(albumDTO.getId()); // Usarás el ID del DTO
        } else {
            btnFavorito.setForeground(Color.GRAY);
            // negocio.eliminarFavorito(albumDTO.getId());
        }
    }//GEN-LAST:event_btnFavoritoActionPerformed

    private void BtnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSeleccionarActionPerformed
        if (this.albumDTO != null) {
            presentacion.FrmCancionesAlbum ventanaCanciones = new presentacion.FrmCancionesAlbum(this.albumDTO);

            ventanaCanciones.setVisible(true);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No se encontraron datos disponibles para este álbum.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnSeleccionarActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSeleccionar;
    private javax.swing.JToggleButton btnFavorito;
    private javax.swing.JLabel jLabelArtista;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JPanel pnlImagen;
    // End of variables declaration//GEN-END:variables
}
