/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import java.awt.Color;
import dtos.CancionDetallesDTO;
import java.awt.BorderLayout;
import java.awt.Image;
import java.net.URL;
import java.util.function.Consumer;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;

/**
 *
 * @author cinca
 */
public class pnlCancion extends javax.swing.JPanel {
    
    private CancionDetallesDTO cancionDTO;
    
    private Consumer<Boolean> accionFavorito;
    public void setAccionFavorito(Consumer<Boolean> accionFavorito) {
        this.accionFavorito = accionFavorito;
    }
    
    /**
     * Creates new form pnlCancion
     */
    public pnlCancion() {
        initComponents();
        configurarEstiloInicial();
    }
    
    public pnlCancion(CancionDetallesDTO cancionDTO, boolean esFavorita) {
        initComponents();
        configurarEstiloInicial();
        cargarInformacion(cancionDTO, esFavorita);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlImagen = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        lblNombreCancion = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblArtista = new javax.swing.JLabel();
        lblArtista1 = new javax.swing.JLabel();
        lblDuracion = new javax.swing.JLabel();
        btnFavorito = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(109, 79, 130), 3));
        setForeground(new java.awt.Color(109, 79, 130));
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(821, 184));

        lblImagen.setText("imagen");

        javax.swing.GroupLayout pnlImagenLayout = new javax.swing.GroupLayout(pnlImagen);
        pnlImagen.setLayout(pnlImagenLayout);
        pnlImagenLayout.setHorizontalGroup(
            pnlImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImagenLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblImagen)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        pnlImagenLayout.setVerticalGroup(
            pnlImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImagenLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblImagen)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        lblNombreCancion.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblNombreCancion.setText("Nombre de cancion");

        lblGenero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGenero.setText("Genero");

        lblArtista.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblArtista.setText("Artista");

        lblArtista1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblArtista1.setText("Duracion:");

        lblDuracion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDuracion.setText("0.0");

        btnFavorito.setText("★");
        btnFavorito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFavoritoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(pnlImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreCancion)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblArtista1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDuracion))
                            .addComponent(lblGenero))
                        .addContainerGap(505, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblArtista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFavorito)
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombreCancion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblGenero)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lblArtista))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFavorito, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblArtista1)
                            .addComponent(lblDuracion))
                        .addGap(27, 27, 27))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFavoritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavoritoActionPerformed
        boolean seleccionado = btnFavorito.isSelected();

        if (seleccionado) {
            btnFavorito.setForeground(new Color(147, 112, 219));
        } else {
            btnFavorito.setForeground(Color.GRAY);
        }
              
        if (accionFavorito != null) {
            accionFavorito.accept(seleccionado);
        }
    }//GEN-LAST:event_btnFavoritoActionPerformed
    
    public void cargarInformacion(CancionDetallesDTO cancionDTO, boolean esFavorita) {
        this.cancionDTO = cancionDTO;

        if (cancionDTO == null) {
            lblNombreCancion.setText("Cancion sin informacion");
            lblGenero.setText("Genero no disponible");
            lblArtista.setText("Artista no disponible");
            lblDuracion.setText("Sin duracion");
            cargarImagen(null);
            return;
        }

        lblNombreCancion.setText(valorOMensaje(cancionDTO.getNombre(), "Cancion sin nombre"));
        lblGenero.setText(valorOMensaje(cancionDTO.getGenero(), "Genero no disponible"));
        lblArtista.setText(valorOMensaje(cancionDTO.getNombreArtista(), "Artista no disponible"));
        lblDuracion.setText(valorOMensaje(cancionDTO.getDuracion(), "Sin duracion"));
        setToolTipText(valorOMensaje(cancionDTO.getNombreAlbum(), "Album no disponible"));
        cargarImagen(cancionDTO.getImagenAlbum());
        
        if (esFavorita) {
            btnFavorito.setSelected(true);
            btnFavorito.setForeground(new Color(147, 112, 219)); // Morado
        } else {
            btnFavorito.setSelected(false);
            btnFavorito.setForeground(Color.GRAY); // Gris
        }
    }

    private void configurarEstiloInicial() {
        setMaximumSize(new java.awt.Dimension(821, 184));
        btnFavorito.setForeground(Color.GRAY);

        lblNombreCancion.setForeground(Color.WHITE);
        lblGenero.setForeground(Color.WHITE);
        lblArtista.setForeground(Color.WHITE);
        lblArtista1.setForeground(Color.WHITE);
        lblDuracion.setForeground(Color.WHITE);
        
        pnlImagen.setLayout(new BorderLayout());
        lblImagen.setHorizontalAlignment(SwingConstants.CENTER);
        lblImagen.setVerticalAlignment(SwingConstants.CENTER);
        pnlImagen.removeAll();
        pnlImagen.add(lblImagen, BorderLayout.CENTER);
    }
    
    /**
     * Carga la imagen de la cancion, que en realidad es la portada del album
     * al que pertenece, ya que la cancion no tiene imagen propia.
     */
    private void cargarImagen(String rutaImagen) {
        
        if (rutaImagen == null || rutaImagen.isBlank()) {
            lblImagen.setIcon(null);
            lblImagen.setText("Sin imagen");
            return;
        }

        URL url = getClass().getResource("/imagenes/" + rutaImagen);

        if (url == null) {
            lblImagen.setIcon(null);
            lblImagen.setText("Imagen no disponible");
            return;
        }

        ImageIcon icono = new ImageIcon(url);
        Image imagen = icono.getImage().getScaledInstance(120, 120, Image.SCALE_SMOOTH);

        lblImagen.setIcon(new ImageIcon(imagen));
        lblImagen.setText("");
    }


    private String valorOMensaje(String valor, String mensaje) {
        return valor == null || valor.trim().isEmpty() ? mensaje : valor.trim();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnFavorito;
    private javax.swing.JLabel lblArtista;
    private javax.swing.JLabel lblArtista1;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNombreCancion;
    private javax.swing.JPanel pnlImagen;
    // End of variables declaration//GEN-END:variables
}
