/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

/**
 *
 * @author USUARIO
 */
public class PnlMenuLateral extends javax.swing.JPanel {

    /**
     * Creates new form PnlMenuLateral
     */
    public PnlMenuLateral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlFondo = new javax.swing.JPanel();
        LblInicio = new javax.swing.JLabel();
        LblAlbumes = new javax.swing.JLabel();
        LblArtistas = new javax.swing.JLabel();
        LblCanciones = new javax.swing.JLabel();
        LblPerfil = new javax.swing.JLabel();
        BtnInsert = new javax.swing.JButton();
        BtnCerrarSesion = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(235, 603));
        setMinimumSize(new java.awt.Dimension(235, 603));
        setPreferredSize(new java.awt.Dimension(235, 603));

        PnlFondo.setBackground(new java.awt.Color(51, 51, 51));
        PnlFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(144, 104, 225)));

        LblInicio.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        LblInicio.setText("Inicio");

        LblAlbumes.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        LblAlbumes.setText("Albumes");

        LblArtistas.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        LblArtistas.setText("Artistas");

        LblCanciones.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        LblCanciones.setText("Canciones");

        LblPerfil.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        LblPerfil.setText("Perfil");

        BtnInsert.setBackground(new java.awt.Color(109, 79, 130));
        BtnInsert.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        BtnInsert.setText("Insert Masivo");
        BtnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInsertActionPerformed(evt);
            }
        });

        BtnCerrarSesion.setBackground(new java.awt.Color(0, 0, 0));
        BtnCerrarSesion.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        BtnCerrarSesion.setText("Cerrar sesion");
        BtnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlFondoLayout = new javax.swing.GroupLayout(PnlFondo);
        PnlFondo.setLayout(PnlFondoLayout);
        PnlFondoLayout.setHorizontalGroup(
            PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFondoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblPerfil)
                    .addComponent(LblArtistas)
                    .addComponent(LblAlbumes)
                    .addComponent(LblInicio)
                    .addComponent(LblCanciones))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        PnlFondoLayout.setVerticalGroup(
            PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFondoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(LblInicio)
                .addGap(51, 51, 51)
                .addComponent(LblArtistas)
                .addGap(58, 58, 58)
                .addComponent(LblAlbumes)
                .addGap(50, 50, 50)
                .addComponent(LblCanciones)
                .addGap(51, 51, 51)
                .addComponent(LblPerfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(BtnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnInsertActionPerformed

    private void BtnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCerrarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCerrarSesion;
    private javax.swing.JButton BtnInsert;
    private javax.swing.JLabel LblAlbumes;
    private javax.swing.JLabel LblArtistas;
    private javax.swing.JLabel LblCanciones;
    private javax.swing.JLabel LblInicio;
    private javax.swing.JLabel LblPerfil;
    private javax.swing.JPanel PnlFondo;
    // End of variables declaration//GEN-END:variables
}
